import type { IconInfo } from '../types';

export const DEFAULTS_ICONS: [string, IconInfo][] = [
	[
		'add_20_regular.svg',
		{
			id: 'Add',
			name: 'add',
			region: '',
			type: 'regular',
			size: 20,
			file: 'add_20_regular.svg',
		},
	],
	[
		'subtract_20_regular.svg',
		{
			id: 'Subtract',
			name: 'subtract',
			region: '',
			type: 'regular',
			size: 20,
			file: 'subtract_20_regular.svg',
		},
	],
	[
		'calculator_20_regular.svg',
		{
			id: 'Calculator',
			name: 'calculator',
			region: '',
			type: 'regular',
			size: 20,
			file: 'calculator_20_regular.svg',
		},
	],
	[
		'chevron_up_down_20_regular.svg',
		{
			id: 'ChevronUpDown',
			name: 'chevron_up_down',
			region: '',
			type: 'regular',
			size: 20,
			file: 'chevron_up_down_20_regular.svg',
		},
	],
	[
		'error_circle_20_regular.svg',
		{
			id: 'ErrorCircle',
			name: 'error_circle',
			region: '',
			type: 'regular',
			size: 20,
			file: 'error_circle_20_regular.svg',
		},
	],
	[
		'keyboard_tab_20_regular.svg',
		{
			id: 'KeyboardTab',
			name: 'keyboard_tab',
			region: '',
			type: 'regular',
			size: 20,
			file: 'keyboard_tab_20_regular.svg',
		},
	],
	[
		'arrow_enter_left_20_regular.svg',
		{
			id: 'ArrowEnterLeft',
			name: 'arrow_enter_left',
			region: '',
			type: 'regular',
			size: 20,
			file: 'arrow_enter_left_20_regular.svg',
		},
	],
	[
		'keyboard_shift_uppercase_20_regular.svg',
		{
			id: 'KeyboardShiftUppercase',
			name: 'keyboard_shift_uppercase',
			region: '',
			type: 'regular',
			size: 20,
			file: 'keyboard_shift_uppercase_20_regular.svg',
		},
	],
	[
		'dismiss_20_regular.svg',
		{
			id: 'Dismiss',
			name: 'dismiss',
			region: '',
			type: 'regular',
			size: 20,
			file: 'dismiss_20_regular.svg',
		},
	],
	[
		'slash_forward_20_regular.svg',
		{
			id: 'SlashForward',
			name: 'slash_forward',
			region: '',
			type: 'regular',
			size: 20,
			file: 'slash_forward_20_regular.svg',
		},
	],
	[
		'arrow_up_20_regular.svg',
		{
			id: 'ArrowUp',
			name: 'arrow_up',
			region: '',
			type: 'regular',
			size: 20,
			file: 'arrow_up_20_regular.svg',
		},
	],
	[
		'arrow_down_20_regular.svg',
		{
			id: 'ArrowDown',
			name: 'arrow_down',
			region: '',
			type: 'regular',
			size: 20,
			file: 'arrow_down_20_regular.svg',
		},
	],
	[
		'arrow_right_20_regular.svg',
		{
			id: 'ArrowRight',
			name: 'arrow_right',
			region: '',
			type: 'regular',
			size: 20,
			file: 'arrow_right_20_regular.svg',
		},
	],
	[
		'arrow_left_20_regular.svg',
		{
			id: 'ArrowLeft',
			name: 'arrow_left',
			region: '',
			type: 'regular',
			size: 20,
			file: 'arrow_left_20_regular.svg',
		},
	],
	[
		'spacebar_20_regular.svg',
		{
			id: 'Spacebar',
			name: 'spacebar',
			region: '',
			type: 'regular',
			size: 20,
			file: 'spacebar_20_regular.svg',
		},
	],
	[
		'home_20_regular.svg',
		{
			id: 'Home',
			name: 'home',
			region: '',
			type: 'regular',
			size: 20,
			file: 'home_20_regular.svg',
		},
	],
	[
		'backspace_20_regular.svg',
		{
			id: 'Backspace',
			name: 'backspace',
			region: '',
			type: 'regular',
			size: 20,
			file: 'backspace_20_regular.svg',
		},
	],
	[
		'chevron_up_20_regular.svg',
		{
			id: 'ChevronUp',
			name: 'chevron_up',
			region: '',
			type: 'regular',
			size: 20,
			file: 'chevron_up_20_regular.svg',
		},
	],
	[
		'chevron_right_20_regular.svg',
		{
			id: 'ChevronRight',
			name: 'chevron_right',
			region: '',
			type: 'regular',
			size: 20,
			file: 'chevron_right_20_regular.svg',
		},
	],
	[
		'chevron_down_20_regular.svg',
		{
			id: 'ChevronDown',
			name: 'chevron_down',
			region: '',
			type: 'regular',
			size: 20,
			file: 'chevron_down_20_regular.svg',
		},
	],
	[
		'chevron_left_20_regular.svg',
		{
			id: 'ChevronLeft',
			name: 'chevron_left',
			region: '',
			type: 'regular',
			size: 20,
			file: 'chevron_left_20_regular.svg',
		},
	],
	[
		'navigation_20_regular.svg',
		{
			id: 'Navigation',
			name: 'navigation',
			region: '',
			type: 'regular',
			size: 20,
			file: 'navigation_20_regular.svg',
		},
	],
	[
		'square_multiple_20_regular.svg',
		{
			id: 'SquareMultiple',
			name: 'square_multiple',
			region: '',
			type: 'regular',
			size: 20,
			file: 'square_multiple_20_regular.svg',
		},
	],
	[
		'phone_vibrate_20_regular.svg',
		{
			id: 'PhoneVibrate',
			name: 'phone_vibrate',
			region: '',
			type: 'regular',
			size: 20,
			file: 'phone_vibrate_20_regular.svg',
		},
	],
	[
		'search_20_regular.svg',
		{
			id: 'Search',
			name: 'search',
			region: '',
			type: 'regular',
			size: 20,
			file: 'search_20_regular.svg',
		},
	],
	[
		'eye_20_regular.svg',
		{
			id: 'Eye',
			name: 'eye',
			region: '',
			type: 'regular',
			size: 20,
			file: 'eye_20_regular.svg',
		},
	],
	[
		'eye_off_20_regular.svg',
		{
			id: 'EyeOff',
			name: 'eye_off',
			region: '',
			type: 'regular',
			size: 20,
			file: 'eye_off_20_regular.svg',
		},
	],
	[
		'password_20_regular.svg',
		{
			id: 'Password',
			name: 'password',
			region: '',
			type: 'regular',
			size: 20,
			file: 'password_20_regular.svg',
		},
	],
	[
		'settings_20_regular.svg',
		{
			id: 'Settings',
			name: 'settings',
			region: '',
			type: 'regular',
			size: 20,
			file: 'settings_20_regular.svg',
		},
	],
	[
		'document_20_regular.svg',
		{
			id: 'Document',
			name: 'document',
			region: '',
			type: 'regular',
			size: 20,
			file: 'document_20_regular.svg',
		},
	],
	[
		'document_arrow_up_20_regular.svg',
		{
			id: 'DocumentArrowUp',
			name: 'document_arrow_up',
			region: '',
			type: 'regular',
			size: 20,
			file: 'document_arrow_up_20_regular.svg',
		},
	],
];
